version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - npm install  serverless-offline
  build:
    commands:
      - aws configure
      - serverless deploy
  post_build:
    commands:
      - echo build complete
